### PR TITLE
refactor autogenerating a getList, so it can be reused

### PR DESCRIPTION
**Pull request by stanistan**
Now if overriding the `Model::getList` and you want to also keep default behavior without rewriting it, you can do:

``` php
<?php

class artist extends Model
{

    public static function getList($a, $count = false)
    {
        $lst = \getList::autoGenerate(static::getAQL())
            ->addJoin('tour on tour.artist_id = artist.id')
            ->defineFilters([
                'tour' => [
                    'callback' => function($val) use($lst) {
                        $list->where[] = "tour.name = '{$val}'";
                    }
                ]
            ]);

        return $count ? $list->getCount($a) : $list->select($a);
    }

}

/// .... usage

$artist = artist::getOne([
    'name' => 'Red Hot Chili Peppers',
    'tour' => 'Coachella'
]);

```

### CODE REVIEW

**Comment by will123195** [comment]
when you `addJoin()` does that join always happen?

**Comment by stanistan** [comment]
In this case yes, you can also add join as a callback to a specific filter.

``` php
<?php

    public static function getList($a, $count = false)
    {
        $list = \getList::autoGenerate(static::getAQL())
            ->defineFilters([
                'tour' => [
                    'callback' => function($val) use($list) {

                        $list->addJoin('tour on tour.artist_id = artist.id');

                        $val = \getList::prepVal($val);
                        $list->where[] = "tour.name in {$val}";
                    }
                ]
            ]);

        return $count ? $list->getCount($a) : $list->select($a);
    }
```

**Comment by will123195** [comment]
that makes sense... cool

**Comment by will123195** [comment]
what is `prepVal()`?

also, what are the possible values for a filter other than `callback`?

**Comment by stanistan** [comment]
`prepVal()` uses `arrayify` and `implode` in case the argument given to the callback is an array.

---

Filter can also have a key `operator`, which is used in conjunction with `search`.

If a filter is defined with an operator, the callback will be applied to a value if it is passed to search:

Example:

``` php
<?php
->defineFilters([
    'tour' => [
         'operator' => 'tour',
         //...
    ]
]);

// ..............

$result = artist::getList([
    'search' => 'tour: Coachella'
]);

```

This allows for a kind of google style searching implementation.

**Pull request merged**
